### ISSUE TITLE
Missing Configure and Deploy Windows Information Protection Policies by using Intune Lab 0601

### ISSUE THREAD

**Issue by ttomovski** [MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator#80]
# Module: 06
#### Step: 00

Description of issue Lab0601 missing
In the official guide for this MD-102 course there should be 3 labs in Learning path 06:

**Lab 0601 Configure and Deploy Windows Information Protection Policies by using Intune** 
Lab 0602 Configuring Endpoint security using Intune
Lab 0603 Configuring Disk Encryption using Intune

However, Lab 0601 regarding Windows Information Protection is removed. Is there alternative lab for that?

**Comment by craigbeeremct** [comment]
I believe the lab was not copied from MD-101 to MD-102 because WIP has been retired.

[https://techcommunity.microsoft.com/t5/windows-it-pro-blog/announcing-the-sunset-of-windows-information-protection-wip/ba-p/3579282](https://techcommunity.microsoft.com/t5/windows-it-pro-blog/announcing-the-sunset-of-windows-information-protection-wip/ba-p/3579282)

**Comment by ttomovski** [comment]
I appreciate the feedback Craig, thank you. However, it might be time then the content to be adjusted for this course :)

**Comment by MSFT-rstearman** [comment]
@ttomovski Thanks for bringing this to our attention. Craig is correct as the lab was removed due to WIP being retired. Currently Lab 0601 is Configuring Endpoint security using Intune
Lab 0602 is Configuring Disk Encryption using Intune
as per the TPG. Can you provide an upload of where you are seeing the referenced labs?

**Comment by MSFT-rstearman** [comment]
Closing this as there has not been any response to my last comment.
