### ISSUE TITLE
Lab 0802 - needs removing from the course

### ISSUE THREAD

**Issue by WigF1** [MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator#85]
This lab needs either removing from the course or rewriting to omit the self-deploy profile. It is **physically** impossible to **successfully** complete the lab with the self-deploy profile attached. 

Per https://learn.microsoft.com/en-us/autopilot/self-deploying

![image](https://github.com/MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator/assets/12164329/0fb6f20a-3de4-41b8-bf74-6246a8a71b2a)

If a student follows the lab steps and uses SEA-W10-CL3, the deployment profile will fail to assign. This means they will do nothing other than a reset.

![image](https://github.com/MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator/assets/12164329/ffecbcf9-8828-4383-b991-c3aa93389e20)

![image](https://github.com/MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator/assets/12164329/5802cd21-61ba-4c97-b684-7a78ddba3a79)

The profile does at least apply to the Windows 11 VMs because they do report a TPM2.0. 

![image](https://github.com/MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator/assets/12164329/9a7ee75e-ac13-408f-b2c5-945eb88e2993)

**However**, because the TPM is virtual, it will eventually time out per the note from the first image above.

![image](https://github.com/MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator/assets/12164329/e55857ef-b7ca-4db3-9c07-d343208fddaf)

So, again, we either need to remove the lab from the course **or** rewrite it so that something is changed on the machine after the initial Autopilot deployment so that students can actually see the effect of an Autopilot reset. Otherwise, they just sit and wait 30 minutes for literally nothing.

**Comment by MSFT-rstearman** [comment]
Thank you for bringing this to our attention. I will review these and determine which direction we will take.

**Comment by MSFT-rstearman** [comment]
We are in the process of a full lab review and will take this into consideration.

**Comment by AaronHorn** [comment]
@MSFT-rstearman - Shouldn’t this issue be reopened and remain open until it is resolved for visibility? A class of 10 of us have spent a few hours playing with this, while we checked the issues tab, no one though to check the closed issues for the several references to this.

The lab clearly needs to be discontinued or MSFT need to provide more information than ‘we’re working on new labs’. Yet last month someone updated references to include a workstation called SEA-WS3-GTL? This doesn’t exist in our environment (Skillable) and I don’t see how this lab could ever work since MS state Hyper V VMs cannot do TPM attestation unless there is now a way to do it with virtual devices (if so, tell us how!)

**Comment by WigF1** [comment]
@AaronHorn hard agree.
