### ISSUE TITLE
Lab 0602: Configuring Disk Encryption Using Intune starting bitlocker error

### ISSUE THREAD

**Issue by dpapkin** [MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator#96]
# Module: 00
#### Step: 11

Description of issue
1) GUI change
On the Configurations settings page, expand Administrative Templates, scroll down to Windows Components > BitLocker Drive Encryption > Operating System Drives and then configure the following options, leaving all other options to their defaults:

SHOULD BE
On the Configurations settings page, expand Operating System Drives and then configure the following options, leaving all other options to their defaults:

2) Some additional options need to be set or client will get error when Bitlocker is enabled

Task 2 Step4 , when click SYNC, will get error

![image](https://github.com/user-attachments/assets/7b73798d-0710-4381-bcb4-59b68a9a7bf8)

To fix, set these settings also
<img width="178" alt="image" src="https://github.com/user-attachments/assets/699f36bf-913a-4fc8-84bd-2f990e4402f6">

Repro steps:

1.
1.
1.

**Comment by WigF1** [comment]
Waiting for #93 to be merged which fixes this.

**Comment by WigF1** [comment]
edit: I just reread the full details. I'm not seeing the same issue you are when following the steps as written nor did my students when running through it. 

The order was out of sequence, which is fixed in #93 but the only thing I can see you added in the screenshot which isn't already contained in the instructions was 'Allow data recovery agent'. As I said, my students nor I have had any issues deploying Bitlocker without the DRA selected. It's never been a requirement for the bitlocker lab.

**Comment by awillslo** [comment]
I just finished MD 102 this past week and zero issues with bitlocker myself.

**Comment by WigF1** [comment]
Yup, just did it too. 9 students no dramas with the instructions.
